# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Scala CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Build and test
        run: |
          sbt clean compile test

      - name: Run coverage and report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          CI: true
          CI_NAME: "github-actions"
          CI_BUILD_ID: ${{ github.run_id }}
          CI_BUILD_NUMBER: ${{ github.run_number }}
          CI_JOB_ID: ${{ github.run_id }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          COVERALLS_SERVICE_NAME: "github"
          COVERALLS_SERVICE_JOB_ID: ${{ github.run_id }}
        run: |
          echo "CI_NAME=$CI_NAME"
          echo "CI_BUILD_ID=$CI_BUILD_ID"
          echo "CI_BUILD_NUMBER=$CI_BUILD_NUMBER"
          echo "CI_JOB_ID=$CI_JOB_ID"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          sbt clean coverage test
          sbt coverageReport
          sbt coverageAggregate
          sbt coveralls -Dcoveralls.serviceName=$COVERALLS_SERVICE_NAME


